[package]
name = "veos"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
bitflags = "0.7.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
